### ISSUE TITLE
Can't get rflx_pdblips:toggleDuty to work

### ISSUE THREAD

**Issue by Kraleemil** [vjota2/rflx_pdblips#2]
I have tried to use TriggerEvent('rflx_pdblips:toggleDuty, onDutyBoolean) -- true or false but can't get it to work

**Comment by vjota2** [comment]
Hey, can you show me preview of you implementation?

**Comment by Kraleemil** [comment]
> Hey, can you show me preview of you implementation?

I did just see you reply to me i can do it tomorrow or if its easier then can i also discord

**Comment by Kraleemil** [comment]
Here is the code

```
RegisterCommand("togglegps", function(source, args, rawCommand)
	if not args then 
		--TriggerEvent('chatMessage', source, "[SYNTAX]", {255, 0, 0}, "/gps [on/off]") 
        TriggerEvent('chatMessage', source, "[SYNTAX]", {255, 0, 0}, "/togglegps [on/off]") 
        --print("[^4SYNTAX]^0 /togglegps [on/off]")
	else
	local a = tostring(args[1])
		if a == "off" then
            TriggerEvent('rflx_pdblips:toggleDuty, false)
		elseif a == "on" then
            TriggerEvent('rflx_pdblips:toggleDuty, true)
		else
			--TriggerEvent('chatMessage', source, "[SYNTAX]", {255, 0, 0}, "/gps [on/off]") 
            print("[^4SYNTAX]^0 /gps [on/off]")
		end
	end
end, false) 
```

**Comment by Kraleemil** [comment]
You can contact me on discord 𝒦𝓇𝒾𝓈𝓉𝒾𝒶𝓃 𝐸𝓂𝒾𝓁# 0 0 0 1

**Comment by Kidoo96** [comment]
You miss ' in the TriggerEvent('rflx_pdblips:toggleDuty', false) after toggleDuty you need ' and here is the same 

TriggerEvent('rflx_pdblips:toggleDuty, true) , thats why dont work.

@vjota2  if you can edit it in the readme

**Comment by vjota2** [comment]
Sure, thanks for pointing that out

**Comment by Kraleemil** [comment]
> You miss ' in the TriggerEvent('rflx_pdblips:toggleDuty', false) after toggleDuty you need ' and here is the same 
> 
> TriggerEvent('rflx_pdblips:toggleDuty, true) , thats why dont work.
> 
> @vjota2  if you can edit it in the readme

🤦‍♂️ I am blind and dum

**Comment by vjota2** [comment]
Currently I'm unable to edit it on phone, gonna be home in like 2 weeks or so, cuz I'm helping with recovery after tornado hit our country..
